pipeline {
  agent none

  stages{
    stage("build"){
      agent {
        docker { 
          image 'maven:3.6.1'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      when{
        changeset "**/worker/*"
      }

      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    stage('test'){
      agent {
        docker { 
          image 'maven:3.6.1'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      when{
        changeset "**/worker/*"
      }

      steps{
        echo 'Running Unit Test on worker app.'
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }
    stage('package'){
      agent {
        docker { 
          image 'maven:3.6.1'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      when{
        branch 'master'
        changeset "**/worker/*"
      }

      steps{
        echo 'Packaging worker app'
        dir('worker'){
          sh 'mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }
    stage('docker-package'){
      agent any
      when{
        changeset "**/worker/*"
      }

      steps{
        echo 'Packaging worker app in Docker container'
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'hub.docker.com') {
            def workerImage = docker.build("yadkov/worker:${env.BUILD_ID}", "./worker/")
            workerImage.push()
            workerImage.push("latest")
          }
        }
      }
    }

  }
  
  post{
    always{
      echo 'Building multibranch pipeline for worker is completed..'
    }
    failure{
      slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    success{
      slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
  }  
}
